### ISSUE TITLE
Docker 설치 및 사용 가이드

### ISSUE THREAD

**Issue by NohJunYoung** [NohJunYoung/MFC#10]
# Docker 설치
https://da2uns2.tistory.com/entry/Docker-%EB%8F%84%EC%BB%A4-%EC%8B%9C%EC%9E%91%ED%95%98%EA%B8%B0-1-%EB%8F%84%EC%BB%A4-%EC%84%A4%EC%B9%98%ED%95%98%EA%B8%B0

# React Docker Settings

## Create Dockerfile
#최상위 경로에 Dockerfile  이름으로 파일 생성

- [`/Dockerfile`](./react_docker/Dockerfile)

```
# Step 1
# base image for Step 1: Node 10
FROM node:16 AS builder
WORKDIR /app
## 프로젝트의 모든 파일을 WORKDIR(/app)로 복사한다
COPY . .
## Nest.js project를 build 한다
RUN npm install
# RUN npm run build

# Step 2
## base image for Step 2: Node 10-alpine(light weight)
FROM node:16-alpine
WORKDIR /app
## Step 1의 builder에서 build된 프로젝트를 가져온다
COPY . .

# RUN npm install -g serve

## application 실행
# CMD ["serve", "-s", "build"]
CMD ["npm", "run", "start"]
```

## Create docker-compose.yml

- 최상위 경로에 docker-compose.yml 이름 파일 생성 후 해당 내용 붙여넣기
- [`docker-compose.yml`](react_docker/docker-compose.yml)
- 포트 변경 시 environment:PORT, ports 의 번호(3000)를 동일하게 변경해주어야함

```
version: "3"

services:
  api:
    environment:
      PORT: 3000
      REACT_APP_URI: prod
      NODE_ENV: prod
    build: .
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
    restart: always
```

## Excute Docker

- go application root folder

```
cd ~/github_repos/mfc-react-user
```

- execute docker container

```
docker-compose up -d --build
```

## 도커 명령어

- `docker ps` 도커 컨테이너 리스트
- `docker rm <CONTAINER ID>` 도커 컨테이너 삭제
- `docker images` 도커 이미지 리스트
- `docker rmi <IMAGE ID>` 도커 이미지 삭제
- `docker-compose up -d` 현재 폴더의 도커를 백그라운드에서 실행
- `docker-compose up -d --build` 현재 폴더의 도커를 백그라운드에서 재빌딩한 후에 실행
- `docker-compose down` 현재 폴더에서 실행된 컨테이너를 다운
- `docker logs <CONTAINER ID>` 도커 컨테이너 로그
